version: "3"
services:
  bio:
    build:
      context: ./
      dockerfile: Dockerfile
      args: 
        HAB_AUTH_TOKEN: 0
    privileged: true
    command: bash -c "./biome-habitats/scripts/build-latest-reticulum.sh"

