version: "3"
services:
  bio:
    image: 283786857250.dkr.ecr.eu-west-1.amazonaws.com/rdl-biome-updater:latest
    build:
      context: ./
      dockerfile: Dockerfile
      args: 
        HAB_AUTH_TOKEN: 0
    privileged: true
    command: bash -c "./biome-habitats/scripts/build-latest-reticulum.sh"

